package test.queue.server;

public enum TaskState {
	Task_NEED_TO_DISPATCH,
	TASK_DISPATCHED,
	FILE_TRANSIMMITED,
	PARSE_ERROR,
	PARSE_COMPLETE,
	RESULT_RECEIVED,
	CHECH_DISPATCHED,
	CHECK_SUCCESSED
}
